version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /images
    destination: /var/www/html/
  - source: /lib
    destination: /var/www/html/
  - source: /styles
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start-server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: root